name: "Build Mimir C++ Library"
description: "Composite action to build Mimir C++ library with individual configuration inputs"

inputs:
  env:
    description: "Environment variables"
    required: false
  os:
    description: "Operating system"
    required: true
  cc:
    description: "C compiler"
    required: true
  cxx:
    description: "C++ compiler"
    required: true
  compiler_version:
    description: "Compiler version"
    required: true
  build_type:
    description: "Build type (e.g., Release, Debug)"
    required: true
  build_tests:
    description: "Whether to build tests"
    required: false
    default: "True"
  skip_testing:
    description: "Whether to execute tests"
    required: false
    default: "True"
  skip_pymimir:
    description: "Whether to skip building Python bindings"
    required: false
    default: "True"

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Environment
      uses: ./.github/.actions/setup-environment
      with:
        os: ${{ inputs.os }}
        cc: ${{ inputs.cc }}
        cxx: ${{ inputs.cxx }}
        compiler-version: ${{ inputs.compiler_version }}
        build-type: ${{ inputs.build_type }}
        use-cache: true
        set-env-vars: true

    - name: Build Mimir
      shell: bash
      env: ${{ inputs.env }}
      run: |
        conan \
        build . \
        --build=missing \
        -s compiler.cppstd=gnu20 \
        -c tools.build:skip_test='${{ inputs.skip_tests }}' \
        -o pymimir/*:with_pybindings='${{ (inputs.skip_pymimir == 'False') }}'