name: Build Source Distribution

on: [push]

jobs:
  build_sdist:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies and requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools twine 'conan==2.8.1'

    - name: Configure Conan
      run: |
          conan profile detect --name default
          
          # replace any cppstd=(gnu)XX entry in the compiler.cppstd line with cppstd=20
          profile=$(conan profile path default)
          awk '{ sub(/compiler\.cppstd=gnu?[0-9]+/, "compiler.cppstd=gnu20"); print }' "$profile" > tmpfile && mv tmpfile "$profile"

    - name: Build source distribution
      run: python setup.py sdist

    - name: Check distribution
      run: twine check dist/*

#    - name: Upload to PyPI
#      if: github.repository_owner == 'simon-stahlberg'
#      env:
#        TWINE_USERNAME: __token__
#        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
#      run: twine upload --skip-existing --repository-url https://upload.pypi.org/legacy/ dist/*
