name: Build Source Distribution

on: [push]

jobs:
  build_wheels:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies and requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools twine

    - name: Build source distribution
      run: python setup.py sdist

#    - name: Upload to PyPI
#      if: github.repository_owner == 'simon-stahlberg'
#      env:
#        TWINE_USERNAME: __token__
#        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
#      run: twine upload --skip-existing --repository-url https://upload.pypi.org/legacy/ dist/*
