name: Build Wheels

on: [ push ]

jobs:
  build_wheels:
    name: Build wheels • ${{ matrix.os }} • ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # macos-13 is x86_64, macos-14 is arm64
        include:
          - os: macos-13
            arch: x86_64
          - os: macos-14
            arch: arm64
            # revisit this when github actions provides aarch64 linux runners at the end of 2024
            # (emulation for cross compilation takes too long)
            # - os: ubuntu-latest
            #   arch: aarch64
            #   skip: '*musllinux*'
            # - os: ubuntu-latest
            #   arch: aarch64
            #   skip: '*manylinux*'
          - os: ubuntu-latest
            arch: x86_64
            skip: '*musllinux*'
          - os: ubuntu-latest
            arch: x86_64
            skip: '*manylinux*'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Python 3.8 is a necessary workaround for macos with arm64, otherwise arch errors occur
      # revisit once support for python 3.8 is dropped and wheels are built from 3.9 onwards
      - name: Set up Python
        uses: actions/setup-python@v5
        # see https://github.com/actions/setup-python/issues/862
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: 1
        with:
          python-version: "3.8"

      - name: Install dependencies and requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel twine 'conan>=2.8.1,<3.0.0'

      - name: Clone Conan-Center-Index
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        working-directory: ${{ github.workspace }}
        run: |
          # clone conan-center-index to get the recipes locally
          git clone https://github.com/conan-io/conan-center-index.git
          
          echo "CONAN_CENTER_PATH=${{ github.workspace }}/conan-center-index" >> "$GITHUB_ENV"

      - name: Configure Conan
        run: |
          conan_home="$HOME/.conan2"
          export CONAN_HOME="$conan_home"
          conan profile detect --name default
          echo "CONAN_HOME=$conan_home" >> "$GITHUB_ENV"

      - name: Prebuild Conan dependencies
        if: ${{ startsWith(matrix.os, 'macos') }}
        env:
          CONAN_HOME: ${{ env.CONAN_HOME }}
        run: |
          export MACOSX_DEPLOYMENT_TARGET=11.0
          ./configure.sh \
          --only_install

      - name: Setup LIBC Conan Dependencies Identifier
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          echo -e "None\nNone" > "$HOME/libc-identifier.txt"
          echo "LIBC_CACHE_ID_FILE=$HOME/libc-identifier.txt" >> "$GITHUB_ENV"

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_SKIP: ${{ matrix.skip }}
          CIBW_ENVIRONMENT_LINUX: >
            CONAN_HOME="${{ env.CONAN_HOME }}"
            CONAN_CENTER_CLONE_PATH="${{ env.CONAN_CENTER_PATH }}"
            LIBC_CACHE_ID_FILE="${{ env.LIBC_CACHE_ID_FILE }}"
          CIBW_ENVIRONMENT_MACOS: >
            CONAN_HOME="${{ env.CONAN_HOME }}"
            MACOSX_DEPLOYMENT_TARGET=11.0
          CIBW_BUILD_VERBOSITY: "1"
        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: "{package}/pyproject.toml"

      - name: Sanitize skip name
        run: |
          if [ -z "${{ matrix.skip }}" ]; then
            echo "sanitized_name=none" >> $GITHUB_ENV
          else
            sanitized_name=$(echo "${{ matrix.skip }}" | sed 's/\*/not_/' | sed 's/\*//')
            echo "sanitized_name=$sanitized_name" >> $GITHUB_ENV
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ runner.os }}-${{ matrix.arch }}-${{ env.sanitized_name }}
          path: ./wheelhouse/*.whl

      # merge the wheels of manylinux and musllinux into one artifact (will only rename for other platforms)
      - name: Merge artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          # The name of the artifact that the artifacts will be merged into
          # Optional. Default is 'merged-artifacts'
          name: cibw-wheels-${{ runner.os }}-${{ matrix.arch }}
          # A glob pattern matching the artifacts that should be merged.
          # Optional. Default is '*'
          pattern: cibw-wheels-${{ runner.os }}-${{ matrix.arch }}-*
          # If true, the artifacts will be merged into separate directories.
          # If false, the artifacts will be merged into the root of the destination.
          # Optional. Default is 'false'
          separate-directories: false
          # If true, the artifacts that were merged will be deleted.
          # If false, the artifacts will still exist.
          # Optional. Default is 'false'
          delete-merged: true
          # The level of compression for Zlib to be applied to the artifact archive.
          # The value can range from 0 to 9.
          # For large files that are not easily compressed, a value of 0 is recommended for significantly faster uploads.
          # Optional. Default is '6'
          compression-level: 9
