name: Build Wheels

on: [push]

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies and requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel twine cibuildwheel

    - name: Build wheels
      run: cibuildwheel --platform linux --output-dir wheelhouse
      env:
        CIBW_BUILD_VERBOSITY: "1"

#    - name: Upload to PyPI
#      if: github.repository_owner == 'simon-stahlberg'
#      env:
#        TWINE_USERNAME: __token__
#        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
#      run: twine upload --skip-existing --repository-url https://upload.pypi.org/legacy/ wheelhouse/*
