name: Build CPP Library

on: [ push, pull_request ]

jobs:
  load-config:
    uses: ./.github/workflows/read-matrix-file.yml
    with:
      matrix_file: 'build-matrix.json'

  build:
    needs: load-config
    name: ${{ matrix.config.os }} • ${{ matrix.config.cc }}-${{ matrix.config.compiler_version }} • ${{ matrix.config.build_type }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.load-config.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4
      - name: Run .github/.actions/cpp-build
        uses: ./.github/.actions/cpp-build
        with:
          os: ${{ matrix.config.os }}
          cc: ${{ matrix.config.cc }}
          cxx: ${{ matrix.config.cxx }}
          compiler_version: ${{ matrix.config.compiler_version }}
          build_type: ${{ matrix.config.build_type }}
          skip_testing: 'True'
          skip_pymimir: 'True'