name: Integration Tests - Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: gcc:14.2

    steps:
    - name: Checkout Mimir
      uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install CMake
      run: |
        apt-get update
        apt-get install -y cmake

    - name: Configure, Build, and Install Dependencies
      run: |
        cd tests/integration/dependencies
        cmake -S . -B build -DCMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/tests/integration/dependencies/installs"
        cmake --build build

    - name: Build and Test Project
      run: |
        cd tests/integration
        cmake -S . -B build -DCMAKE_PREFIX_PATH="$GITHUB_WORKSPACE/tests/integration/dependencies/installs"
        cmake --build build
