name: Integration Tests

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Mimir
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Build Test Project
      run: |
        cmake -S tests/integration -B tests/integration/build -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=conan_provider.cmake
        cmake --build tests/integration/build

    - name: Run Test Project
      run: |
        cd tests/integration/build
        ctest -V
