name: PIP Install & Test

on: [ push ]

jobs:
  load-config:
    uses: ./.github/workflows/read-matrix-file.yml
    with:
      matrix_file: 'build-matrix.json'

  build:
    needs: load-config
    name: ${{ matrix.config.os }} • Py-${{ matrix.python-version }} • ${{ matrix.config.cc }}-${{ matrix.config.compiler_version }} • ${{ matrix.config.build_type }}
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.load-config.outputs.matrix) }}
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Run .github/.actions/setup-environment
        uses: ./.github/.actions/setup-environment
        with:
          os: ${{ matrix.config.os }}
          cc: ${{ matrix.config.cc }}
          cxx: ${{ matrix.config.cxx }}
          compiler-version: ${{ matrix.config.compiler_version }}
          build-type: ${{ matrix.config.build_type }}
          python-version: ${{ matrix.python-version }}
          use-cache: true
          set-env-vars: true

      - name: Install dependencies and requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools pytest

      - name: Build and install
        run: python -m pip install --verbose .[test]
        env:
          PYMIMIR_BUILD_TYPE: ${{ matrix.config.build_type }}

      - name: Test
        run: pytest python/tests
