name: pip install and test

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies and requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools pytest

      - name: Build and install
        run: python -m pip install --verbose .[test]
        env:
          PYMIMIR_DEBUG_BUILD: 1

      - name: Test
        run: pytest python/tests
