name: PIP Install & Test

on: [push]

jobs:
  config_reader:
    uses: ./.github/workflows/read-build-matrix.yml

  build:
    needs: config_reader
    name: ${{ matrix.config.os }} • Py-${{ matrix.python-version }} • ${{ matrix.config.cc }}-${{ matrix.config.compiler_version }} • ${{ matrix.config.build_type }}
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.config_reader.outputs.matrix) }}
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/.actions/setup-environment
        with:
          os: ${{ matrix.config.os }}
          cc: ${{ matrix.config.cc }}
          cxx: ${{ matrix.config.cxx }}
          compiler-version: ${{ matrix.config.compiler_version }}
          build-type: ${{ matrix.config.build_type }}
          python-version: ${{ matrix.python-version }}
          use-cache: true
          set-env-vars: true

      - name: Install dependencies and requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools pytest

      - name: Build and install
        run: python -m pip install --verbose .[test]
        env:
          PYMIMIR_BUILD_TYPE: ${{ matrix.config.build_type }}

      - name: Test
        run: pytest python/tests
