name: Load Build Matrix

on:
  workflow_call:
    outputs:
      matrix:
        description: "The matrix strategy from the build-matrix.json file"
        value: ${{ jobs.matrix-setup.outputs.matrix }}

jobs:
  matrix-setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          TASKS=$(echo $(cat .github/workflows/build-matrix.json) | sed 's/ //g')
          echo "matrix=$TASKS" >> $GITHUB_OUTPUT