name: Unit And Integration Tests

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Mimir
        uses: actions/checkout@v4

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.28.x'

      - name: Show cmake version
        run: cmake --version

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Conan
        run: pip install conan

      # Release
      - name: Release Configure Mimir
        shell: bash
        run: >
          cmake 
          -S . 
          -B build_debug 
          -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=conan_provider.cmake 
          -DCMAKE_BUILD_TYPE=Release 
          -DBUILD_TESTS=ON 

      - name: Release Build Mimir
        run: |
          cmake --build build_release

      - name: Upload build folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_release_${{ matrix.os }}
          path: build_release/
          retention-days: 1

  unit-test:
    needs: build
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Download release folder
        uses: actions/download-artifact@v4
        with:
          pattern: build_release_${{ matrix.os }}
          path: build/release

      - name: Release Test
        working-directory: build/release/tests/unit
        run: GTEST_OUTPUT=xml:test-results/ GTEST_COLOR=1 ctest -V

      - name: Install
        run: |
          cmake --install build/release --prefix install

      - name: Upload installation as artifact
        uses: actions/upload-artifact@v4
        with:
          name: install_${{ matrix.os }}
          path: install
          retention-days: 1

  integration-test:
    needs: unit-test
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Mimir
        uses: actions/checkout@v4

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.28.x'

      - name: Show cmake version
        run: cmake --version

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Conan
        run: pip install conan

      - name: Download Installed Mimir
        uses: actions/download-artifact@v4
        with:
          pattern: install_${{ matrix.os }}
          path: install

      - name: Configure Test Project
        shell: bash
        run: >
          cmake 
          -S tests/integration 
          -B tests/integration/build 
          -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=conan_provider.cmake
          -DCMAKE_PREFIX_PATH=install

      - name: Build Test Project
        run: |
          cmake --build tests/integration/build

      - name: Run Test Project
        run: |
          cd tests/integration/build
          GTEST_COLOR=1 ctest -V