name: Googletest Unit Tests

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Mimir
      uses: actions/checkout@v2
      with:
        ref: main

      # Debug
    - name: Debug Configure Mimir
      run: >
        cmake 
          -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=conan_provider.cmake 
          -DCMAKE_BUILD_TYPE=Debug 
          -DBUILD_TESTS=ON 
          -S . 
          -B build_debug 

      # Debug
    - name: Debug Build Mimir
      run: |
        cmake --build build_debug

    - name: Debug Test
      working-directory: build_debug/tests/unit
      run: GTEST_OUTPUT=xml:test-results/ GTEST_COLOR=1 ctest -V

    # Release
    - name: Release Configure Mimir
      run: >
        cmake 
          -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=conan_provider.cmake 
          -DCMAKE_BUILD_TYPE=Release 
          -DBUILD_TESTS=ON 
          -S . 
          -B build_debug 

    - name: Release Build Mimir
      run: |
        cmake --build build_release

    - name: Release Test
      working-directory: build_release/tests/unit
      run: GTEST_OUTPUT=xml:test-results/ GTEST_COLOR=1 ctest -V
